### PR TITLE
Fix issue #10 : numeric task_id is now well processed

### PR DESCRIPTION
**Pull request by fbaligand**
@purbon 
As promised, I just created a new PR to fix issue #10, with a clean history.

=> Can you review it ?

### CODE REVIEW

**Comment by purbon** [comment]
please jenkins, test this.

**Comment by purbon** [comment]
please jenkins, test this.

**Comment by fbaligand** [comment]
@purbon 
Now that Jenkins build passed successfully, can you merge the PR ?
http://build-eu-00.elastic.co/job/logstash-plugin-filter-aggregate_PR/2/

**Comment by purbon** [comment]
@fbaligand yeah, was going to do that this morning :+1: as we spoke all LGTM.

**Comment by fbaligand** [comment]
Nice  :+1:

**Comment by fbaligand** [comment]
Thank you @purbon !
I will make PR for "core-api-v1" branch tonight !

**Comment by fbaligand** [comment]
@purbon 
Does jenkins will automatically a 2.0.3 release ? 
Or should I make the release ? I mean post release in rubygems.org

**Comment by purbon** [comment]
@fbaligand no automatic process, I can trigger it or you can do it yourself. your call :+1:

**Comment by fbaligand** [comment]
@purbon This is so much beautiful when it is a tool who does the work :)
So can you trigger the release ?

**Comment by purbon** [comment]
on my way.

**Comment by fbaligand** [comment]
And this is done ! 
Thank you very much !

**Comment by purbon** [comment]
you're welcome!

**Comment by fbaligand** [comment]
@purbon 
Now this PR is merged, can you close PR #11 ? (PR #11 is fixed by PR #12)

**Pull request merged**
