### PR TITLE
 fix issue #5 : report branch core-api-v1 to master

### PR DESCRIPTION
**Pull request by fbaligand**

### CODE REVIEW

**Comment by fbaligand** [comment]
@purbon 
I merged the branch core-api-v1 to master.
Can you review it ?

**Comment by fbaligand** [comment]
@purbon 
Thanks for the merge.
I realize that it just miss one thing : update to CHANGELOG.md.
I have changed CHANGELOG.md on core-api-v1 there 15 minutes, but not reported on master branch.

=> Can you do the report ? 
Or must I open a new pull request for that ?

**Comment by purbon** [comment]
@fbaligand might be faster if you do it. thanks man!

**Comment by fbaligand** [comment]
@purbon 
OK, I will make the pull request tonight :)

**Pull request merged**
