### PR TITLE
Fix issue #5 on branch master (logstash 2)

### PR DESCRIPTION
**Pull request by fbaligand**
Fix issue #5.
When code call raises an exception, the error is logged and the event is tagged '_aggregateexception'.
Thus, it avoids logstash crash.

### CODE REVIEW

**Comment by purbon** [comment]
it looks like this PR is the same as #6, I would say we should have only one and then backport to the other branch. Like this review would be easy, what do you think?

**Comment by fbaligand** [comment]
I totally agree with you.
This pull request is indeed a merge from #6.

So we can make review only on #6. And then, I will report the branch onto the master for this pull request.

**Comment by purbon** [comment]
@fbaligand sorry took me long time to come back, too much as always. As boths PR as identical, I think I'm more comfortable reviewing and testing this, and then we can squash an easy backport to v1, you can move and close #6 so we have no confusion. Is this ok for you?

**Comment by purbon** [comment]
Oh, bad day my day today, I saw we started with #6, so lets close this one and focus only on #6, ok.

**Comment by purbon** [comment]
As both's PR are identical, but vs different branches, closing this in benefit of #6.

**Pull request closed without merging**
