### PR TITLE
Updated docs regarding necessity of setting filter workers to 1

### PR DESCRIPTION
**Pull request by robin13**

### CODE REVIEW

**Comment by fbaligand** [comment]
Hi @robin13 ,

Firstable, sorry for my late answer.

Then few things :
- each time I give you a remark, you don't have to close the pull request and start another. You can simply make a new commit & push, and the PR will automatically integrate it.
- the update is only about documentation, so I don't plan to make a new release for that, just a documentation update on logstash reference.
=> Can you revert your changes in CHANGELOG.md and logstash-filter-aggregate.gemspec ?

**Comment by robin13** [comment]
Done.

**Comment by fbaligand** [comment]
Perfect !

**Comment by fbaligand** [comment]
please jenkins, test it

**Comment by fbaligand** [comment]
please jenkins, test this.

**Comment by fbaligand** [comment]
jenkins, test it

**Comment by fbaligand** [comment]
LGTM

**Comment by fbaligand** [comment]
Hi @robin13, 

I just created a new issue in logstash, so that your documentation updates are displayed in logstash reference documentation :
https://github.com/elastic/logstash/issues/4307

**Pull request merged**
